// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSrGc2Dz7SPWd-YCaujotqzcAygjDg_co',
    appId: '1:562359943408:web:f698746eff73a3d7e54235',
    messagingSenderId: '562359943408',
    projectId: 'marchaatletica-b19fa',
    authDomain: 'marchaatletica-b19fa.firebaseapp.com',
    storageBucket: 'marchaatletica-b19fa.firebasestorage.app',
    measurementId: 'G-MZKF4KNWPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCvZFVThDKsAOYc7Y08eVB9CofB5QR1LE',
    appId: '1:562359943408:android:cf6be1100dcc3ca1e54235',
    messagingSenderId: '562359943408',
    projectId: 'marchaatletica-b19fa',
    storageBucket: 'marchaatletica-b19fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM-G8UP6t4fomUeNx7A0KkEgLjp7CDOiA',
    appId: '1:562359943408:ios:2c77531e33c9cd02e54235',
    messagingSenderId: '562359943408',
    projectId: 'marchaatletica-b19fa',
    storageBucket: 'marchaatletica-b19fa.firebasestorage.app',
    iosBundleId: 'com.example.marcha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM-G8UP6t4fomUeNx7A0KkEgLjp7CDOiA',
    appId: '1:562359943408:ios:2c77531e33c9cd02e54235',
    messagingSenderId: '562359943408',
    projectId: 'marchaatletica-b19fa',
    storageBucket: 'marchaatletica-b19fa.firebasestorage.app',
    iosBundleId: 'com.example.marcha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSrGc2Dz7SPWd-YCaujotqzcAygjDg_co',
    appId: '1:562359943408:web:e5cda8a51308d710e54235',
    messagingSenderId: '562359943408',
    projectId: 'marchaatletica-b19fa',
    authDomain: 'marchaatletica-b19fa.firebaseapp.com',
    storageBucket: 'marchaatletica-b19fa.firebasestorage.app',
    measurementId: 'G-ZJDTDVKWVF',
  );
}
